/**
 * Shared icon mapping helper for tool configurations.
 * Maps backend/config string representations of icons to display emojis.
 */
export function getToolEmoji(icon: string): string {
  const emojiMap: Record<string, string> = {
    CurrencyRupeeIcon: '₹',
    HomeIcon: '🏠',
    TruckIcon: '🚗',
    UserIcon: '👤',
    AcademicCapIcon: '🎓',
    CheckBadgeIcon: '✅',
    ChartBarIcon: '📊',
    BanknotesIcon: '💳',
    ArrowTrendingUpIcon: '📈',
    ShieldCheckIcon: '🛡',
    BuildingOfficeIcon: '🏢',
    SunIcon: '☀️',
    ReceiptPercentIcon: '🧾',
    DocumentChartBarIcon: '📃',
    CreditCardIcon: '💳',
    HomeModernIcon: '🏡',
    CalculatorIcon: '🧮',
    GlobeAltIcon: '🌍',
    GiftIcon: '🎁',
    ChartBarSquareIcon: '📊',
    ArrowsRightLeftIcon: '↔️',
    UsersIcon: '👥',
    ClipboardDocumentListIcon: '📋',
    PresentationChartBarIcon: '📑',
    ScaleIcon: '⚖️',
    StarIcon: '⭐',
    CurrencyBitcoinIcon: '₿',
    ArrowPathIcon: '🔄',
    ChartPieIcon: '🥧',
    CodeBracketIcon: '{ }',
    LinkIcon: '🔗',
    ShieldCheck: '🔒',
    FingerPrintIcon: '🔑',
    LockClosedIcon: '🔒',
    MagnifyingGlassIcon: '🔍',
    ClockIcon: '⏰',
    SwatchIcon: '🎨',
    CircleStackIcon: '🗄',
    DocumentDuplicateIcon: '📋',
    KeyIcon: '🔑',
    DocumentTextIcon: '📝',
    PaintBrushIcon: '🖌',
    ArrowsPointingOutIcon: '↔',
    ArchiveBoxIcon: '📦',
    ScissorsIcon: '✂️',
    QrCodeIcon: '⬛',
    PhotoIcon: '🖼',
    WindowIcon: '🖥',
    SparklesIcon: '✨',
    HeartIcon: '❤️',
    WrenchScrewdriverIcon: '🔧',
    MapIcon: '🗺',
    BriefcaseIcon: '💼',
    DocumentIcon: '📄',
    PresentationChartLineIcon: '📉',
  };
  return emojiMap[icon] ?? '🔧';
}
