/* eslint-disable no-console, @typescript-eslint/no-explicit-any */
// Regenerates src/components/shared/iconRegistry.ts — run: npx tsx scripts/gen-icons.ts
import { writeFileSync } from 'node:fs';
import * as Icons from 'lucide-react';
import { TOOLS } from '../src/config/tools';
import { MODULES } from '../src/config/modules';
import { MODULE_METADATA } from '../src/config/moduleMetadata';
import { ICON_MAPPING } from '../src/components/shared/iconMapping';
const names = new Set<string>();
const add = (n?: string) => { if (!n) return; const r = ICON_MAPPING[n] || n; if ((Icons as any)[r]) names.add(r); else console.log('UNRESOLVED', n); };
TOOLS.forEach(t => add(t.icon)); MODULES.forEach(m => add(m.icon));
Object.values(MODULE_METADATA).forEach((m: any) => (m.whyUse||[]).forEach((w: any) => add(w.icon)));
Object.values(ICON_MAPPING).forEach(v => (Icons as any)[v] && names.add(v));
['HelpCircle'].forEach(n => names.add(n));
const list = [...names].sort();
writeFileSync('src/components/shared/iconRegistry.ts', `// AUTO-GENERATED by scripts (icons used by tools, modules and metadata). Explicit imports keep the bundle tree-shakeable.\nimport type { ComponentType, CSSProperties } from 'react';\nimport {\n${list.map(n=>`  ${n},`).join('\n')}\n} from 'lucide-react';\n\nexport type IconComponent = ComponentType<{\n  size?: number;\n  className?: string;\n  strokeWidth?: number;\n  style?: CSSProperties;\n  'aria-hidden'?: boolean | 'true' | 'false';\n}>;\n\nexport const ICON_REGISTRY: Record<string, IconComponent> = {\n${list.map(n=>`  ${n},`).join('\n')}\n};\n`);
console.log('icons', list.length);
